@startuml
!include style.puml

' show +/-/# instead of icons
skinparam classAttributeIconSize 0
skinparam classMethodIconSize 0   ' (optional, if you also want methods)

skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
class JsonUserPrefsStorage
}

class "<<interface>>\nStorage" as Storage
class StorageManager

package "AddressBook Storage" #F4F6F6{
class "<<interface>>\nAddressBookStorage" as AddressBookStorage
class JsonAddressBookStorage
class JsonSerializableAddressBook
class JsonAdaptedPerson
class JsonAdaptedPatient {
  - List<String> notes
  - List<List<String>> appointments
}
class JsonAdaptedCaretaker
class JsonAdaptedTag
}

}

show JsonAdaptedPatient fields

class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPatient
JsonAdaptedPatient --|> JsonAdaptedPerson
JsonAdaptedPatient --> "0..1" JsonAdaptedCaretaker
JsonAdaptedPatient --> "0..1" JsonAdaptedTag
JsonAdaptedCaretaker --|> JsonAdaptedPerson

@enduml
