name: Deploy MarkBind Site
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./docs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i -g markbind-cli
      - run: markbind deploy --ci
      - name: Add .nojekyll to gh-pages
        run: |
          git fetch origin gh-pages
          touch .nojekyll
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .nojekyll
          git commit -m "Add .nojekyll file" || echo "No changes to commit"
          git push origin gh-pages
        working-directory: ${{ github.workspace}}
